---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: game-service
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: hide-and-seek-game-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
spec:
  to:
    kind: Service
    name: hide-and-seek-game-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name:  hide-and-seek
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: hide-and-seek-frontend
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
spec:
  to:
    kind: Service
    name: hide-and-seek-frontend
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: leaderboard-service
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: hide-and-seek-leaderboard-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
spec:
  to:
    kind: Service
    name: hide-and-seek-leaderboard-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: place-service
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: hide-and-seek-place-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
spec:
  to:
    kind: Service
    name: hide-and-seek-place-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: player-service
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: hide-and-seek-player-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
spec:
  to:
    kind: Service
    name: hide-and-seek-player-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
---