name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
      - name: Build with Maven
        run: mvn -B clean install